### ISSUE TITLE
Remove duplicated triples from KGs

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#2]
Please, remove all duplicates.

**Comment by ddomingof** [comment]
Is this already fixed? @cthoyt

**Comment by cthoyt** [comment]
Closed with d996d09

See: https://github.com/SmartDataAnalytics/BioKEEN/commit/d996d09aec0e9afaac1f0aee3409e97ab94e812e#diff-5b0f6c118889a2d4f7d4200255e210a7L41
