### ISSUE TITLE
bio2bel_interpro 0.1.1 requires networkx-1.11 -> conflict with pybel 0.12.2

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#24]
Installation: **`pip install git+https://github.com/SmartDataAnalytics/BioKEEN.git`**
Command: **`biokeen start`**
**`pip freeze`**:  [requirements.txt](https://github.com/SmartDataAnalytics/BioKEEN/files/3079211/requirements.txt)

**Exception:**
Current Step: Please select the database(s) you want to train on:
 1: compath
 2: hippie
 3: kegg
 4: mirtarbase
 5: msig
 6: reactome
 7: sider
 8: wikipathways
 9: drugbank
10: adeptus
11: hsdn
12: interpro
13: ddr
> Please select one or more of the options: 12
Collecting bio2bel_interpro
  Using cached https://files.pythonhosted.org/packages/f9/c9/7148f1691829f3641943b13a06520ea9f081f6f24357a9256edaf8495e08/bio2bel_interpro-0.1.1-py3-none-any.whl
Requirement already satisfied: click in ./test/lib/python3.7/site-packages (from bio2bel_interpro) (7.0)
Requirement already satisfied: pandas in ./test/lib/python3.7/site-packages (from bio2bel_interpro) (0.24.2)
Collecting networkx==1.11 (from bio2bel_interpro)
  Using cached https://files.pythonhosted.org/packages/d3/2c/e473e54afc9fae58dfa97066ef6709a7e35a1dd1c28c5a3842989322be00/networkx-1.11-py2.py3-none-any.whl
Requirement already satisfied: sqlalchemy in ./test/lib/python3.7/site-packages (from bio2bel_interpro) (1.3.2)
Requirement already satisfied: tqdm in ./test/lib/python3.7/site-packages (from bio2bel_interpro) (4.31.1)
Requirement already satisfied: bio2bel>=0.0.9 in ./test/lib/python3.7/site-packages (from bio2bel_interpro) (0.2.1)
Requirement already satisfied: pybel[deployment]>=0.11.1 in ./test/lib/python3.7/site-packages (from bio2bel_interpro) (0.13.1)
  pybel 0.13.1 does not provide the extra 'deployment'
Requirement already satisfied: python-dateutil>=2.5.0 in ./test/lib/python3.7/site-packages (from pandas->bio2bel_interpro) (2.8.0)
Requirement already satisfied: numpy>=1.12.0 in ./test/lib/python3.7/site-packages (from pandas->bio2bel_interpro) (1.16.2)
Requirement already satisfied: pytz>=2011k in ./test/lib/python3.7/site-packages (from pandas->bio2bel_interpro) (2019.1)
Requirement already satisfied: decorator>=3.4.0 in ./test/lib/python3.7/site-packages (from networkx==1.11->bio2bel_interpro) (4.4.0)
Requirement already satisfied: easy-config in ./test/lib/python3.7/site-packages (from bio2bel>=0.0.9->bio2bel_interpro) (0.2.0)
Requirement already satisfied: requests-file in ./test/lib/python3.7/site-packages (from pybel[deployment]>=0.11.1->bio2bel_interpro) (1.4.3)
Requirement already satisfied: requests in ./test/lib/python3.7/site-packages (from pybel[deployment]>=0.11.1->bio2bel_interpro) (2.21.0)
Requirement already satisfied: click-plugins in ./test/lib/python3.7/site-packages (from pybel[deployment]>=0.11.1->bio2bel_interpro) (1.1.1)
Requirement already satisfied: bel-resources in ./test/lib/python3.7/site-packages (from pybel[deployment]>=0.11.1->bio2bel_interpro) (0.0.2)
Requirement already satisfied: pyparsing in ./test/lib/python3.7/site-packages (from pybel[deployment]>=0.11.1->bio2bel_interpro) (2.4.0)
Requirement already satisfied: six>=1.5 in ./test/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas->bio2bel_interpro) (1.12.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./test/lib/python3.7/site-packages (from requests->pybel[deployment]>=0.11.1->bio2bel_interpro) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in ./test/lib/python3.7/site-packages (from requests->pybel[deployment]>=0.11.1->bio2bel_interpro) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./test/lib/python3.7/site-packages (from requests->pybel[deployment]>=0.11.1->bio2bel_interpro) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./test/lib/python3.7/site-packages (from requests->pybel[deployment]>=0.11.1->bio2bel_interpro) (2.8)
Requirement already satisfied: multisplitby in ./test/lib/python3.7/site-packages (from bel-resources->pybel[deployment]>=0.11.1->bio2bel_interpro) (0.0.1)
pybel 0.13.1 has requirement networkx>=2.1, but you'll have networkx 1.11 which is incompatible.
Installing collected packages: networkx, bio2bel-interpro
  Found existing installation: networkx 2.3
    Uninstalling networkx-2.3:
      Successfully uninstalled networkx-2.3
Successfully installed bio2bel-interpro-0.1.1 networkx-1.11
🍩 failed to import bio2bel_interpro

**Comment by cthoyt** [comment]
Fixed with the latest release of [bio2bel-interpro](https://pypi.org/project/bio2bel-interpro/)
