### ISSUE TITLE
A problem of installation based on Linux

### ISSUE THREAD

**Issue by jacklin18** [SmartDataAnalytics/BioKEEN#28]
ImportError: cannot import name 'HAS_COMPONENT' from 'pybel.constants' (/home/linxuan/Anaconda3/envs/biokeen/lib/python3.7/site-packages/pybel/constants.py)

I don't know how to solve it.

**Comment by cthoyt** [comment]
Sorry, we removed this relationship in PyBEL v0.14. I think we can pin the dependencies to "pybel<0.14.0" in the setup.cfg and it will solve it

**Comment by cthoyt** [comment]
Also, we have begun a branch where we're upgrading to PyBEL 14 (but this requires updating a lot of bio2bel dependencies too and it will take a long time... maybe a christmas break project?)

**Comment by jacklin18** [comment]
Hi, I download it again and thank you for your quick reply. I think BioKEEN will give me a great help to learn from it.
