### ISSUE TITLE
Hyperparameter optimization

### ISSUE THREAD

**Issue by hevalatas** [SmartDataAnalytics/BioKEEN#31]
Hi, I wonder if it is possible to do hyperparameter optimization with the grid search option rather than the random search. Moreover, are the results of all hyperparameter combinations selected during optimization also available, in addition to the results of the best parameters?

**Comment by cthoyt** [comment]
hi @hevalatas, please see the main PyKEEN repository at https://github.com/pykeen/pykeen. This repository has been superceded and we can't provide any additional support here
