### ISSUE TITLE
Check whether the download of the database was interrupted

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#9]
If the download of a database was interrupted, please make sure that download continues when called again or make sure that the process starts from the beginning without requiring the user to do something

**Comment by cthoyt** [comment]
This issue should probably live in the Bio2BEL repository - there might be a way to have some integrity checking. One example after a fast google search could use this: https://stackoverflow.com/a/24047999/5775947

**Comment by mali-git** [comment]
> This issue should probably live in the Bio2BEL repository - there might be a way to have some integrity checking. One example after a fast google search could use this: https://stackoverflow.com/a/24047999/5775947

I agree, its better to deal with this issue within Bio2BEL. 
The solution looks good.
